services:
  api:
    build: .
    command: python -m uvicorn main:app --host 0.0.0.0 --port 3000 --reload --reload-include *
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose: 
      - 5432

volumes:
  postgres_data: