services:
  api:
    build: .
    command: python -m uvicorn main:app --host 0.0.0.0 --port 3000 --reload --reload-include *
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5678:5678
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  test_db:
    container_name: postgres_test_db
    image: postgres:15.1-alpine
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_HOST: ${TEST_POSTGRES_HOST}
      POSTGRES_PORT: ${TEST_POSTGRES_PORT}
    ports:
      - 5433:5432

volumes:
  postgres_data:
  test_postgres_data:
