"""add inserted date to user table

Revision ID: dc32bf0e7736
Revises: 63153affc701
Create Date: 2023-08-15 04:49:12.035903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc32bf0e7736'
down_revision = '63153affc701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inserted_date', sa.DateTime(), nullable=False))
    op.alter_column('users', 'activated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'inserted_date')
    # ### end Alembic commands ###
