"""add activated field to user

Revision ID: 63153affc701
Revises: 357d5540eb05
Create Date: 2023-02-07 13:26:49.194849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63153affc701"
down_revision = "357d5540eb05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("users", sa.Column("activated", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET activated = false")
    op.alter_column("users", sa.Column("activated", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activated")
    # ### end Alembic commands ###
